modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="fnaf_mod"
version="3"
displayName="The Five Nights at Freddy's Mod"
credits="Made Using Mcreator, Models By: Mephilis,Rashi,NiksonTF2,ItsIdyllic,Kiseki and Mosdi.Music By: LordSmugDread,GreatPlays, The Host and SomethingFunky.Textures By: Beph,Fredo,ItsIdyllic,Rashi and NiksonTF2. Structures By: Rashi,Mephilis,Beph and ItsIdyllic. Code By: Mephilis Additional Help: WyldDog and Sajevius."
displayURL="https://www.curseforge.com/minecraft/mc-mods/the-five-nights-at-freddys-mod"
logoFile="logo.png"
authors="mephilis,"
description='''
Five Nights at Freddy's in Minecraft!
'''

[[dependencies.fnaf_mod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




